spring:
  config:
    activate:
      on-profile: prod

cors:
  allowed-origins:
    - https://api.betterday.one
    # Apple Login CORS 방지하기 위해 호스트 허용
    - https://appleid.apple.com
  credentials: true
