version: '3.9'
services:
  feelring-mysql:
    image: mysql:8.2.0
    container_name: feelring-db
    restart: always
    ports:
      - 11000:3306
    environment:
      MYSQL_ROOT_PASSWORD: N3f9g4iLKLRErjo
      MYSQL_DATABASE: feelring
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./.docker/mysql/:/var/lib/mysql
      - ./infra/:/docker-entrypoint-initdb.d
    networks:
      - feelring-network

networks:
  feelring-network:
    driver: bridge
    external: true
