spring:
  profiles:
    active: local

  cloud:
    aws:
      credentials:
        access-key: test
        secret-key: test
      sns:
        region:
          static: us-east-1
        topic:
          diary-topic-arn: arn:aws:sns:us-east-1:000000000000:diary-events
