spring:
  config:
    activate:
      on-profile: local

  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:10000/api/v1/auth/oauth2/google
          kakao:
            redirect-uri: http://localhost:10000/api/v1/auth/oauth2/kakao
          apple:
            redirect-uri: http://localhost:10000/api/v1/auth/oauth2/apple
