spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(+MwxbHQlJhB5+bE8qV8H0/NgJDBZ2QexsQZnEoUM4aCWqyIqmCVoYCtdBK7N6/7A46kQp8ttKd/Jbx/4pW+wjIC5iPxcNFj1JOXqJwUBwd6hgaCC2tOhBw==)
            client-secret: ENC(MYPnFyP7GliFDiG7ji91+QyoN3RXJ8jRa6VfiTfzhyA//uYI6dBMd7UwwVFrL3Pf)
            authorization-grant-type: authorization_code
            scope:
              - https://www.googleapis.com/auth/userinfo.profile
              - https://www.googleapis.com/auth/userinfo.email
              - openid
            client-authentication-method: basic
            client-name: Google
          kakao:
            client-id: ENC(J2fEyg3tEaJjcrbZAGMvtCkYlzuq7IoiwGQ7L8V6Il3WRiXVvSg8JmqN2m3/SOvx)
            client-secret: ENC(x0QLNnkuLoxHTacKcoQbnx2vhuieemFxFHz9NSVHH+lQHvtRiOZ83hIEmx4gQKiL)
            authorization-grant-type: authorization_code
            scope:
              - openid
            client-authentication-method: client_secret_post
            client-name: Kakao
          apple:
            client-id: ENC(02pBa5Ln6MTJxqYYZBtRaH4lOFozd1S74pV9yMuA/aE=)
            team-id: ENC(OLaQjdkwbKKGCWBGQ0/wF9YA1P5uaSbX)
            key-id: ENC(kj4Suf3TYsTmENma8zQ7mGzOcWl8rRvk)
            key-path: ENC(/HKHNBtnuQaUrA9w/01tjDTqvf2YSNjTxQ14zdVt6nemP7a28CPA0oaCY/8NQX+N)
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
            client-authentication-method: post
            client-name: Apple
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v1/userinfo
            user-name-attribute: id
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          apple:
            issuer-uri: https://appleid.apple.com
            token-uri: https://appleid.apple.com/auth/token
            public-key-uri: https://appleid.apple.com/auth/keys
            authorization-uri: https://appleid.apple.com/auth/authorize
            user-name-attribute: sub

client:
  connect-timeout: 5000
  read-timeout: 5000
