create table diary (
    created_at timestamp(6),
    deleted_at timestamp(6),
    id bigserial not null,
    updated_at timestamp(6),
    user_id bigint,
    alarm_url varchar(255),
    category varchar(255),
    content varchar(255),
    fcm_token varchar(255),
    uid varchar(255),
    primary key (id)
)

create table users (
    created_at timestamp(6),
    deleted_at timestamp(6),
    id bigserial not null,
    last_login_at timestamp(6),
    last_logout_at timestamp(6),
    updated_at timestamp(6),
    email varchar(255),
    image varchar(255),
    nickname varchar(255),
    password varchar(255),
    provider_id varchar(255),
    provider_name varchar(255) check (provider_name in ('UNKNOWN','DEFAULT','GOOGLE','APPLE','KAKAO','TWITTER','TIKTOK')),
    role varchar(255),
    primary key (id)
)

CREATE TABLE alarms (
	created_at timestamp(6) NULL,
	deleted_at timestamp(6) NULL,
	diary_id int8 NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	updated_at timestamp(6) NULL,
	link varchar(255) NULL,
	CONSTRAINT alarm_pkey PRIMARY KEY (id)
);

CREATE TABLE weekly_report_feelings (
	weekly_report_id int8 NOT NULL,
	"type" varchar(255) NULL,
	CONSTRAINT weekly_report_feelings_type_check CHECK (((type)::text = ANY ((ARRAY['UNKNOWN'::character varying, 'HAPPY'::character varying, 'EXICTED'::character varying, 'RELAXED'::character varying, 'SAD'::character varying, 'ANXIOUS'::character varying, 'ANGRY'::character varying])::text[]))),
	CONSTRAINT fkbs984ommhvr7kxt6e5omt192g FOREIGN KEY (weekly_report_id) REFERENCES public.weekly_reports(id)
);

CREATE TABLE weekly_reports (
	id bigserial NOT NULL,
	"content" text NOT NULL,
	created_at timestamp(6) NULL,
	deleted_at timestamp(6) NULL,
	updated_at timestamp(6) NULL,
	user_id int8 NOT NULL,
	week int4 NOT NULL,
	years int4 NOT NULL,
	CONSTRAINT weekly_reports_pkey PRIMARY KEY (id)
);

CREATE TABLE notices (
	created_at timestamp(6) NOT NULL,
	deleted_at timestamp(6) NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	updated_at timestamp(6) NOT NULL,
	"content" varchar(255) NOT NULL,
	title varchar(255) NOT NULL,
	status varchar(20) DEFAULT 'ACTIVE'::status_enum NOT NULL,
	CONSTRAINT notices_pkey PRIMARY KEY (id)
);
