jwt:
  issuer: BetterDay-Security
  access-token:
    secret-key: secretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkey
    expiration: 2592000 # 30d
  refresh-token:
    secret-key: anotherkeyanotherkeyanotherkeyanotherkeyanotherkeyanotherkey
    expiration: 2592000 # 30d
